/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/'use strict';

(function ($, Drupal) {
  Drupal.behaviors.gutenbergAdmin = {
    attach: function attach() {
      $('.view-reusable-blocks .views-row').click(function (e) {
        $(e.currentTarget).find('input[type="checkbox"]').click();
      });
    }
  };
})(jQuery, Drupal);