/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/'use strict';

function _toConsumableArray(arr) { if (Array.isArray(arr)) { for (var i = 0, arr2 = Array(arr.length); i < arr.length; i++) { arr2[i] = arr[i]; } return arr2; } else { return Array.from(arr); } }

(function (wp, $, Drupal, drupalSettings) {
  var data = wp.data,
      blocks = wp.blocks;
  var _window$DrupalGutenbe = window.DrupalGutenberg.Components,
      DrupalIcon = _window$DrupalGutenbe.DrupalIcon,
      DrupalMediaEntity = _window$DrupalGutenbe.DrupalMediaEntity;


  var gutenberg = drupalSettings.gutenberg || {};
  var isMediaLibraryEnabled = gutenberg['media-library-enabled'] || false;
  var isMediaEnabled = gutenberg['media-enabled'] || false;

  var registerDrupalMedia = function registerDrupalMedia() {
    return new Promise(function (resolve) {
      var category = {
        slug: 'drupal_media',
        title: Drupal.t('Drupal Media')
      };

      var categories = [].concat(_toConsumableArray(data.select('core/blocks').getCategories()), [category]);

      if (isMediaEnabled) {
        data.dispatch('core/blocks').setCategories(categories);
        registerBlock();
      }

      resolve();
    });
  };

  var registerBlock = function registerBlock() {
    var blockId = 'drupalmedia/drupal-media-entity';

    blocks.registerBlockType(blockId, {
      title: Drupal.t('Drupal Media Entity'),
      icon: DrupalIcon,
      category: 'drupal_media',
      supports: {
        align: false,
        html: false,
        reusable: false
      },
      attributes: {
        mediaEntityIds: {
          type: 'array'
        },
        viewMode: {
          type: 'string',
          default: 'default'
        }
      },
      edit: function edit(_ref) {
        var attributes = _ref.attributes,
            className = _ref.className,
            setAttributes = _ref.setAttributes;

        return React.createElement(
          Fragment,
          null,
          React.createElement(DrupalMediaEntity, { attributes: attributes,
            className: className,
            setAttributes: setAttributes,
            isMediaLibraryEnabled: isMediaLibraryEnabled })
        );
      },
      save: function save() {
        return null;
      }
    });
  };

  window.DrupalGutenberg = window.DrupalGutenberg || {};
  window.DrupalGutenberg.registerDrupalMedia = registerDrupalMedia;
})(wp, jQuery, Drupal, drupalSettings);