/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/"use strict";

(function (Drupal, wp) {
  var translate = function translate(value) {
    return Drupal.t(value);
  };
  wp.i18n = {};
  wp.i18n.__ = translate;
  wp.i18n._x = translate;
  wp.i18n._n = function (single, plural, number) {
    return Drupal.formatPlural(number, single, plural);
  };
  wp.i18n.sprintf = translate;
})(Drupal, wp);