/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/'use strict';

(function (drupalSettings, wp) {
  window.wp = wp || {};

  window.userSettings = window.userSettings || {
    secure: drupalSettings.user.permissionsHash,
    time: 1234567,
    uid: drupalSettings.user.uid
  };

  window.wpApiSettings = window.wpApiSettings || {};
  window.wpApiSettingsroot = window.wpApiSettings.root || window.location.origin;
  window.wpApiSettingsnonce = window.wpApiSettings.nonce || '123456789';
  window.wpApiSettingsversionString = window.wpApiSettings.versionString || 'wp/v2/';

  window.postboxes = window.postboxes || {
    add_postbox_toggles: function add_postbox_toggles(page, args) {}
  };

  window.wpEditorL10n = window.wpEditorL10n || {
    tinymce: {
      baseUrl: 'vendor/tinymce',
      settings: {
        external_plugins: [],
        plugins: 'charmap,colorpicker,hr,lists,media,paste,tabfocus,textcolor,fullscreen',
        toolbar1: 'formatselect,bold,italic,bullist,numlist,blockquote,alignleft,aligncenter,alignright,link,unlink,wp_more,spellchecker,kitchensink',
        toolbar2: 'strikethrough,hr,forecolor,pastetext,removeformat,charmap,outdent,indent,undo,redo,wp_help',
        toolbar3: '',
        toolbar4: ''
      },
      suffix: '.min'
    }
  };

  drupalSettings.gutenberg._listeners = {
    init: []
  };

  drupalSettings.gutenberg.addListener = function (type, callback) {

    if (!drupalSettings.gutenberg._listeners[type]) {
      throw new Error('Type ' + type + ' not defined as an event listener type for Drupal Gutenberg.');
    }

    drupalSettings.gutenberg._listeners[type].push(callback);
  };
})(drupalSettings, window.wp);