/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/'use strict';

var _extends = Object.assign || function (target) { for (var i = 1; i < arguments.length; i++) { var source = arguments[i]; for (var key in source) { if (Object.prototype.hasOwnProperty.call(source, key)) { target[key] = source[key]; } } } return target; };

var _wp = wp,
    blocks = _wp.blocks,
    blockEditor = _wp.blockEditor;
var registerBlockType = blocks.registerBlockType;
var InnerBlocks = blockEditor.InnerBlocks;

var __ = Drupal.t;

var settings = {
  title: __('Section'),
  description: __('Section block for template use.'),
  icon: 'media-document',
  attributes: {},

  parent: ['core/paragraph'],

  edit: function edit() {
    return React.createElement(InnerBlocks, { templateLock: false });
  },
  save: function save(_ref) {
    var className = _ref.className;

    return React.createElement(
      'main',
      { className: className },
      React.createElement(InnerBlocks.Content, null)
    );
  }
};

registerBlockType('drupal/section', _extends({ category: 'common' }, settings));