/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/'use strict';

(function (wp, Drupal, DrupalGutenberg) {
  var _DrupalGutenberg$Comp = DrupalGutenberg.Components,
      MediaLibrary = _DrupalGutenberg$Comp.MediaLibrary,
      withNativeDialog = _DrupalGutenberg$Comp.withNativeDialog,
      withGutenbergDialog = _DrupalGutenberg$Comp.withGutenbergDialog;


  wp.hooks.addFilter('editor.MediaUpload', 'core/edit-post/components/media-upload/replace-media-upload', function () {
    return Drupal.isMediaLibraryEnabled() ? withNativeDialog(MediaLibrary) : withGutenbergDialog(MediaLibrary);
  });
})(wp, Drupal, DrupalGutenberg, drupalSettings);