/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/'use strict';

(function (wp, Drupal) {
  var element = wp.element,
      plugins = wp.plugins,
      editPost = wp.editPost;
  var useRef = element.useRef,
      useEffect = element.useEffect;
  var registerPlugin = plugins.registerPlugin;
  var PluginDocumentSettingPanel = editPost.PluginDocumentSettingPanel;


  var FormPanel = function FormPanel() {
    var ref = useRef(null);

    useEffect(function () {
      ref.current.appendChild(document.getElementById('edit-advanced'));

      return function () {
        document.getElementById('gutenberg-sidebar').appendChild(document.getElementById('edit-advanced'));
      };
    }, []);

    return React.createElement('div', { ref: ref });
  };

  var MyDocumentSettingTest = function MyDocumentSettingTest() {
    return React.createElement(
      PluginDocumentSettingPanel,
      { opened: true, className: 'node-setting-plugin', title: 'Node' },
      React.createElement(FormPanel, null)
    );
  };

  registerPlugin('document-setting-test', { render: MyDocumentSettingTest });
})(wp, Drupal);